# DAIR ASSIGNMENT VIII

Name:     Sanidhya \
SID:    22106024 \
Branch: Computer Science Engineering (Data Science)

### Instructions: Please find attached dataset file namely: sample.csv and download it. Apply the following pre-processing steps on the dataset:

####  Tokenization
####  Stemming
####  Lemmatization

In [5]:
import pandas
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import string

In [6]:
data = pandas.read_csv("sample.csv")
data

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0
...,...,...,...,...,...,...,...
88,119330,105859,True,Wed Oct 11 13:50:42 +0000 2017,@105860 I wish Amazon had an option of where I...,119329,119331.0
89,119331,105860,True,Wed Oct 11 13:47:14 +0000 2017,They reschedule my shit for tomorrow https://t...,119330,NaN
90,119332,Tesco,False,Wed Oct 11 13:34:06 +0000 2017,"@105861 Hey Sara, sorry to hear of the issues ...",119333,119334.0
91,119333,105861,True,Wed Oct 11 14:05:18 +0000 2017,@Tesco bit of both - finding the layout cumber...,"119335,119336",119332.0
92,119335,Tesco,False,Wed Oct 11 15:38:07 +0000 2017,@105861 If that doesn't help please DM your fu...,NaN,119333.0

In [7]:
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sksag\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sksag\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [8]:
data['tokens'] = data['text'].apply(word_tokenize)

stemmer = PorterStemmer()
data['stemmed'] = data['tokens'].apply(lambda x: [stemmer.stem(word) for word in x])

lemmatizer = WordNetLemmatizer()
data['lemmatized'] = data['tokens'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

print("Tokenization:")
print(data['tokens'].head())

print("\nStemming:")
print(data['stemmed'].head())

print("\nLemmatization:")
print(data['lemmatized'].head())

Tokenization:
0    [@, AppleSupport, causing, the, reply, to, be,...
1    [@, 105835, Your, business, means, a, lot, to,...
2    [@, 76328, I, really, hope, you, all, change, ...
3    [@, 105836, LiveChat, is, online, at, the, mom...
4    [@, VirginTrains, see, attached, error, messag...
Name: tokens, dtype: object

Stemming:
0    [@, applesupport, caus, the, repli, to, be, di...
1    [@, 105835, your, busi, mean, a, lot, to, us, ...
2    [@, 76328, i, realli, hope, you, all, chang, b...
3    [@, 105836, livechat, is, onlin, at, the, mome...
4    [@, virgintrain, see, attach, error, messag, ....
Name: stemmed, dtype: object

Lemmatization:
0    [@, AppleSupport, causing, the, reply, to, be,...
1    [@, 105835, Your, business, mean, a, lot, to, ...
2    [@, 76328, I, really, hope, you, all, change, ...
3    [@, 105836, LiveChat, is, online, at, the, mom...
4    [@, VirginTrains, see, attached, error, messag...
Name: lemmatized, dtype: object